# Harmformer SE(2)-equivariant (Block P only, with L2 regularizer)
defaults:
  - override /: default

encoder:
  name: "harmformer"
  freeze: true

augmentation:
  skip_geometric: true

contrastive:
  lambda_reg: 0.1
